
export const data = {
    ru: {
      alert1 : "Успешно",
      alert2 : "Вы можете увидеть это в своем профиле!",
      alert3 : "",

//      //header
//       tours : 'Горящие туры',
//       valid: "Регистрация",
//       log: "Логин",
//       nav1:'Туры пo Бишкек',
//       nav2:'Tранспорт',
//       nav3:'Туры пo регионам.',
//       nav4:"Главная",
//       nav5:'О нас',
//       nav6:'Наша школа',
//       nav7:"Другие услуги",
//       nav8:'Вип',
//       nav9:"Карт",
//       //home
//       car:"Кыргызстан",
//       bish:"Бишкек",
//       see:'Посмотреть все программы',
//       regions:"Регионы",
      
//       //first
//       car1:"Туры в Бишкек.Горящие туры и лучшие предложения для вашего отдыха!",
//       firsth1:"Горящие туры в любую страну из Бишкека",
//       firstp:"Туры за границу из Бишкека придутся по душвсем любителям ярких впечатлений. Романтические туры в Париж, Рим и Неаполь. Незабываемый отдых в Таиланде, туры для парочек в райских уголках нашей планеты — живописные Бали и Гоа.  Экскурсионные туры по магической Чехии, величественной Италии,утонченной Франции, колоритной Грузии… Горящие путевки в солнечную Анталию или роскошный Дубай. Любая из предложенных нами стран уникальна, интересна и необыкновенно красива.",
//       buy:"Купить",
//       //Academy
//       comple:"Пройденные",
//        set:"Набор от",
//        october:"20го октября 2020",
//        tur:"1-тур",
//        tur1:"1 декабря 2021 г. - 28 февраля 2021 г.",
//        feb:"27 февраля 2021 г.",
//        tur2:"2-тур",
//        may:"27 мая 2021 - 30 мая 2021",
//        may2:"20 мая 2021 г.",
//        tur3:"3-тур",
//        june:"1 июня 2021 г. - 30 августа 2020 г.",
//        //transport
//        theme:"Услуги при переезде по Кыргызстану",
//        theme1:"Надежно. Безопасно. Оперативно.", 
//        text1:"Услуги хранения имущества в Бишкеке, Кыргызстане",
//        text2:"Обеспечиваем хранение офисной мебели, оборудования, архивов, рекламных материалов и выставочного оборудования в любом объеме и на любой срок, от 1 дня в Бишкеке, Кыргызстане. Надежно!",
//        text3:"Услуги упаковки вещей и техники в Бишкеке, Кыргызстане",
//        text4:"Вся офисная техника, документация, канцелярские принадлежности и личные вещи сотрудников упаковываются и маркируются. Используются качественные упаковочные материалы, при упаковке имущества соблюдаются технологии проведения работ для обеспечения сохранности имущества при перемещении.",
//        text5:"Перевозка имущества",
//        text6:"Имущество заказчика перевозится на оборудованных мебельных фургонах, имеющих внутреннюю обшивку и системы крепления фиксации груза в кузове. Для транспортировки могут быть привлечены автомобили различной грузоподъемности.",
//        text7:"Услуги перестановки мебели в Бишкеке, Кыргызстане",
//        text8:"Осуществляем перестановку офисной мебели в пределах одного этажа и между этажами. Такая необходимость часто возникает при организации ремонта, при ротации персонала или изменении размеров офиса.",
//        text9:'Сборка/разборка мебели в Бишкеке, Кыргызстане',
//        text10:"Наши специалисты обладают многолетним опытом работы, что позволяет им максимально быстро и качественно собрать или разобрать любую офисную мебель. В работе используется профессиональный инструмент.",
//        text11:"Услуги погрузочных и разгрузочных работ в Бишкеке, Кыргызстане",
//        text12:"Погрузочно-разгрузочные работы выполняются в точном соответствии с требованиями безопасности, чтобы обеспечить сохранность имущества клиента и гарантировать максимальную оперативность переезда.",
//        text13:'Грузоперевозки в Бишкеке, Кыргызстане',
//        text14:'При помощи специального оборудования и оснастки наши специалисты организуют перемещение и транспортировку любых тяжеловесных и негабаритных предметов, в т. ч. офисных сейфов, серверного оборудования, архивных систем и другого офисного оборудования.',
//        text15:'Услуги обустройства в новых офисах в Бишкеке, Кыргызстане',


// text16:"Чтобы вы смогли как можно быстрее возобновить работу компании в новом офисе, мы соберем и расставим мебель, разложим вещи сотрудников по местам, повесим жалюзи, вывезем образовавшийся мусор (использованный упаковочный материал).",
//        //footer
//        li1:"ВИП-зал аэропорта",
//        li2:"Туры за рубеж .",
//        li3:"Учеба за границей",
//        li4:"Туры по Кыргызстану",
//        li5:"Транспорт",
//        li6:"Академия",
//        li7:"Оставить отзыв",
//        li8:"Новости компании",
//        li9:"Вакансии",
//        //cart and vip
//       carta1: 'Добро пожаловать в Кыргызстан!',
//       carta2: "Страна заснеженных гор, зеркальных озер и гостеприимства - лучшее для наших гостей",
//       carta3: "Эстетика кыргызского народа",
//       carta4: "Туристические карты",
//       carta5: "Для удобства путешественников мы выпускаем карты и гиды. Вы можете получить их бесплатно во всех наших офисах, а также в некоторых отелях и кафе города Бишкек. Ниже прикреплены карты, которые Вы можете скачать в электронном виде.",
//       carta6: "Бесплатный туристический путеводитель по Бишкеку",
//       carta7: "Бесплатный туристический путеводитель по Кыргызстану",
//       carta8: "Расписание Игр",
//       carta9: "Скачать",
//       vip1: "VIP и Бизнес залы в аэропортах Бишкека, Оша и Алматы: бронь и другие услуги",
//       vip2:"Для особенных путешественников",
//       vip3:"Вы не привыкли тратить драгоценное время на предполетные формальности и желаете особого комфорта?Предлагаем Вам услуги VIP и Бизнес залов",
//       vip4: "В международном аэропорту Манас круглосуточно работает VIP-зал. Это зона для деловых людей, ценящих свое время и комфорт.",
//       three1: "Туры по regionam.Горящие туры и лучшие предложения для вашего отдыха!",
//       three12:"Все туры",
//       three2:"Горящие туры",
//       threeh1:'Туры в Кыргызстан, Китай и страны Центральной Азии из Бишкека',
//       threep:"Компания Kyrgyz Travel в Кыргызстане предлагает соотечественникам и гостям из других стран эксклюзивные туры по Азии.Средняя Азия – это особое состояние души. Это любовь с первого взгляда и на всю жизнь! Красивая природа, сохранившая свой первозданный вид, древние города с богатой историей, таинственные  легенды, памятники архитектуры, шум и ароматы специй восточного базара, самобытная культура и неповторимое гостеприимство и теплота души  местного населения… Все это и многое другое  не оставит вас равнодушными и вы захотите возвращаться сюда снова и снова!",
//       //login
//       login:"Логин",
//       email:'Почта',
//       pass:"Пароль",
//       sign:"Войти",
//       reg: "Зарегистрироваться",
//       question:"Нет аккаунта?",
//       //sign up
//       name:"ваше имя",
//       qua:"Уже есть учетная запись?",
//       account:"создать aкаунт",
//       //userprofile
//       del:"отменить",
//       money:"сом",
//       yet:"you not which yet",
//       your:"your tours",
//       count:"count:"
      },
        en: {
        alert1 : "succes",
        alert2 : "You can see it on your profile!",
        alert3 : "ok",
        }
//       //nav
//       tours:'Hot tours',
//       valid: "SignIn",
//       log: "Login",
//       nav1:'Tours around Bishkek',
//       nav2:"Transport",
//       nav3:"Tours by region.",
//       nav4:"Home",
//       nav5:"About",
//       nav6:"Our school",
//       nav7:"other services",
//       nav8:"Vip",
//       nav9:"Card",
//       //home
//       car:"Kyrgyzstan",
//       bish:"Bishkek",
//       see:'See all programs',
//       regions:"Regions",
//       //first
//       car1:"Tours to Bishkek.Hot tours and the best offers for your vacation!",
//       firsth1:"Last-minute tours to any country from Bishkek", 
//       firstp:"Tours abroad from Bishkek will please to all lovers of vivid impressions. Romantic tours to Paris, Rome and Naples. An unforgettable vacation in Thailand, tours for couples in paradise of our planet - picturesque Bali and Goa. Excursion tours in magical Czech Republic, majestic Italy, sophisticated France, colorful Georgia ...trips to sunny Antalya or luxurious Dubai. Any of of the countries proposed by us is unique, interesting and unusually beautiful.",
//       buy:"buy",
//       //Academy
//       comple:"Completed",
//       set:"Set from",


// october:"20 october 2020",
//       tur:"1st round",
//       tur1:"1 december 2021 г. - 28 февраля 2021 г.",
//       feb:"February 27, 2021",
//       tur2:"2nd round",
//       may:"May 27, 2021 - May 30, 2021",
//       may2:"May 20, 2021",
//       tur3:"3rd round",
//       june:"June 1, 2021 - August 30, 2020.",
//       //transport
//       theme:"Services when moving in Kyrgyzstan",
//       theme1:"Reliable. Safely. Promptly.",
//       text1:"Property storage services in Bishkek, Kyrgyzstan",
//       text2: "We provide storage of office furniture, equipment, archives, advertising materials and exhibition equipment in any volume and for any period, from 1 day in Bishkek, Kyrgyzstan. Reliable!",
//       text3: "Packaging services for things and equipment in Bishkek, Kyrgyzstan",
//       text4: "All office equipment, documentation, stationery and personal belongings of employees are packed and labeled. High-quality packaging materials are used, while packing the property, work procedures are followed to ensure the safety of property during movement.",
//       text5: "Transportation of property",
//       text6: "The customer's property is transported on equipped furniture vans with inner lining and systems for securing cargo in the body. Cars of various carrying capacities can be used for transportation.",
//       text7: "Furniture relocation services in Bishkek, Kyrgyzstan",
//       text8: "We carry out the rearrangement of office furniture within the same floor and between floors. Such a need often arises when organizing repairs, when rotating personnel or changing the size of the office.",
//       text9: 'Assembly / disassembly of furniture in Bishkek, Kyrgyzstan',
//       text10: "Our specialists have many years of experience, which allows them to quickly and efficiently assemble or disassemble any office furniture. A professional tool is used in their work.",
//       text11: "Loading and unloading services in Bishkek, Kyrgyzstan",
//       text12: "Loading and unloading operations are carried out in strict accordance with security requirements to ensure the safety of the client's property and to ensure the maximum speed of the move.",
//       text13: 'Cargo transportation in Bishkek, Kyrgyzstan',
//       text14: 'With the help of special equipment and accessories, our specialists organize the movement and transportation of any heavy and oversized items, including office safes, server equipment, archive systems and other office equipment.',
//       text15: 'Set-up services for new offices in Bishkek, Kyrgyzstan',
//       text16: "So that you can resume the work of the company in the new office as soon as possible, we will collect and arrange furniture, put employees' belongings in their places, hang blinds, take out the resulting garbage (used packaging material).",
//       li1: "VIP lounge of the airport",
//       li2: "Tours abroad .",
//       li3: "Study abroad",
//       li4: "Tours in Kyrgyzstan",
//       li5: "Transport",
//       li6: "Academy",
//       li7: "Leave a review",
//       li8: "Company news",
//       li9: "Jobs",
//       //cart
//       carta1:"Welcome to Kyrgyzstan!",
//       carta2:"A land of snow-capped mountains, mirror-like lakes and hospitality - the best for our guests",
//       carta3:"Aesthetics of the Kyrgyz people",
//       carta4:"Tourist maps",
//       carta5:"For the convenience of travelers, we issue maps and guides. You can get them free of charge in all our offices, as well as in some hotels and cafes in Bishkek. Below are attached maps that you can download electronically.",
//       carta6:"Free travel guide to Bishkek",
//       carta7:"Free travel guide to Kyrgyzstan",
//       carta8:"Games Schedule",
//       carta9:"Download",
//       vip1:"VIP and Business lounges at the airports of Bishkek, Osh and Almaty: booking and other services",
//       vip2:"For special travelers",
//       vip3:"Are you not accustomed to wasting precious time on pre-flight formalities and want special comfort? We offer you VIP and Business Lounge services.",
// vip4:"There is a VIP lounge at Manas international airport around the clock. This is an area for business people who value their time and comfort.",
//       three1:"Tours in the regionam. Hot tours and the best offers for your vacation!",
//       three12:"All tours",
//       three2:"Hot tours",
//       threeh1: 'Tours to Kyrgyzstan, China and Central Asian countries from Bishkek',
//       threep: "Kyrgyz Travel in Kyrgyzstan offers compatriots and guests from other countries exclusive tours in Asia. Central Asia is a special state of mind. This is love at first sight and for life! Beautiful nature that has preserved its original appearance, ancient cities with rich history, mysterious legends, architectural monuments, noise and aromas of spices of the oriental bazaar, original culture and unique hospitality and warmth of the soul of the local population ... All this and much more will not leave you indifferent and you will want to come back here again and again! ",
//       //login
//       login:"Login", 
//       email:'Email',
//       pass:"Password",
//       sign:"Sign in",
//       reg:"Sign up",
//       question:"Don't have an account?",
//       //sign up
//       name:" Your name",
//       qua:"Already have an account?",
//       account:"Create account",
//       //userprofile
//       del:"cancel",
//       money:'som',
//       yet:"вы еще не выбрали",
//       your:"ваши туры",
//       count:"считать:"
//     },
  };
